### ISSUE TITLE
Error when adding Terms

### ISSUE THREAD

**Issue by ElenaRad** [wp-property/wp-property-terms#22]
* [x]  All terms that are in the Terms Tab should match the set up wizard terms. 

* [x]  Error when I try to save a new created Term. 

* [x] The Terms that are default can not be deleted. 

![image](https://cloud.githubusercontent.com/assets/19193013/20605086/3210caf4-b272-11e6-88e5-aa2b2ac61b54.png)

![image](https://cloud.githubusercontent.com/assets/19193013/20605092/3acb1d2a-b272-11e6-9686-cccd621a1563.png)

**Comment by alimuzzaman** [comment]
1. On the setup wizard they are property type not terms.
2. Error on bottom indicate that you don't have any property type (Maybe you don't selected anyone on setup).
3. Should I make Feature & Community Feature delete-able?

**Comment by alimuzzaman** [comment]
There is no default attributes on fresh install.

**Comment by ElenaRad** [comment]
On the setup wizard they are property type not terms.
----> Yes, but we want them to match Property Types from Terms:  
![image](https://cloud.githubusercontent.com/assets/19193013/20606698/60023de0-b27b-11e6-8bfc-eaffdbfd37fe.png)

Error on bottom indicate that you don't have any property type (Maybe you don't selected anyone on setup).
----> Yeah, but when I try adding a type it does not work... 

Should I make Feature & Community Feature delete-able?
---> Yes. People should have the flexibility of adding or deleting fts.
