### ISSUE TITLE
Get rid of Terms Notice

### ISSUE THREAD

**Issue by ElenaRad** [wp-property/wp-property-terms#23]
* [ ] Get rid of Terms notice since it's a part of the core now: 

![image](https://cloud.githubusercontent.com/assets/19193013/20631124/b8395e0e-b33d-11e6-874d-920e82af60c4.png)

**Comment by alimuzzaman** [comment]
This shouldn't be exist anymore. Please check again.

**Comment by ElenaRad** [comment]
good, thanks!
