### ISSUE TITLE
terms not adding

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property-terms#24]
latest wp-property + released/latest terms
![image](https://user-images.githubusercontent.com/5111163/28325809-852ff604-6be7-11e7-9a90-f30278ac34e8.png)

**Comment by andypotanin** [comment]
@Mashenka The `latest` version of WPP has terms pre-packaged into it. If user has legacy standalone terms installed they should be de-activated automatically.

**Comment by Mashenka** [comment]
@andypotanin just FYI it not deactivating automatically. need to add such logic
