### ISSUE TITLE
Fatal error: require_once(): Failed opening required 'RWMB_FIELDS_DIRcheckbox-list.php' (include_path='.:/Applications/MAMP/bin/php/php7.0.8/lib/php')

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property-terms#26]
Issue with latest wp-property branch

Fatal error: require_once(): Failed opening required 'RWMB_FIELDS_DIRcheckbox-list.php' (include_path='.:/Applications/MAMP/bin/php/php7.0.8/lib/php') in /Users/mariakravchenko/sites/wordpress.loc/wp-content/plugins/wp-property-terms/lib/classes/fields/taxonomy.php on line 4

Notice: Use of undefined constant RWMB_FIELDS_DIR - assumed 'RWMB_FIELDS_DIR' in /Users/mariakravchenko/sites/wordpress.loc/wp-content/plugins/wp-property-terms/lib/classes/fields/taxonomy.php on line 4

Warning: require_once(RWMB_FIELDS_DIRcheckbox-list.php): failed to open stream: No such file or directory in /Users/mariakravchenko/sites/wordpress.loc/wp-content/plugins/wp-property-terms/lib/classes/fields/taxonomy.php on line 4

**Comment by SoSeductive** [comment]
Already fixed in `latest` https://github.com/wp-property/wp-property-terms/commit/49c5b0db55f5047bf31238522ac5cf757b228af7#diff-c410958a94e8aaf5fea83f5204c9881e
